# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

# on:
#   release:
#     types: [published]

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Initialize Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade setuptools

    # RUN TESTS
    - name: Run tests/test_1.py
      run: python tests/test_1.py

    # COMPILE PYPI PACKAGE AND PUBLISH
    - name: Compile code
      run: python setup.py sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        # username: danielruneda
        password: ${{ secrets.TEST_PYPI_PASSWORD }}

    # MAKE DOCUMENTATION
    - name: Documentation
      run: cd docs && sphinx-apidoc -f -o . .. && make html
    - name: Deploy documentation
      uses: danielruneda/csklearn@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html

